name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t python-app:latest .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN docker.io
          docker tag python-app:latest janani01/python-app:latest
          docker push janani01/python-app:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Locally
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN docker.io && docker-compose up -d
          echo "Application is accessible at http://localhost:8080"
